[project]
name = "lodeb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.6"
dependencies = [
    "imgui[pygame]",
    "filedialpy",
    "pyte",
]
